# Generated by Django 2.1.7 on 2019-03-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20190319_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='tillWhen',
            new_name='tilWhen',
        ),
    ]
